USE HQT_CSDL
GO

DECLARE @RT INT
EXEC @RT = USP_TaoDonThuoc 6, 'Celpha', 10

--DELETE FROM DONTHUOC WHERE MaDonThuoc = 5

IF @RT = 0
	PRINT N'TẠO ĐƠN THUỐC THẤT BẠI'
ELSE
	PRINT N'TẠO ĐƠN THUỐC THÀNH CÔNG'

--SELECT * FROM tb_ThuocHienHanh()

/* TRANS ROLLBACK */